version: '1'

services:
  #database
  db:
    image: mysql:latest
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: AKBga85bPacDTQ68xsa6xoOa0Uj0RpE
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wp_postgres_user
      MYSQL_PASSWORD: AKBga85bPacDTQ68xsa6xoOa0Uj0RpE
    networks:
      - wordpress_site
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - '8000:80'
    restart: always
    volumes: ['./:/var/www/html']
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wp_postgres_user
      WORDPRESS_DB_PASSWORD: AKBga85bPacDTQ68xsa6xoOa0Uj0RpE
    networks:
      - wordpress_site
networks:
  wordpress_site:
volumes:
  db_data:


